# Generated by Django 4.2 on 2023-05-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corpus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="alt",
            field=models.BooleanField(default=False, verbose_name="Альтернативная"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="corpus.document",
                verbose_name="Документ",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="guid",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="GUID",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="json",
            field=models.JSONField(verbose_name="JSON"),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="sentence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="corpus.sentence",
                verbose_name="Предложение",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="dominant_language",
            field=models.CharField(
                choices=[
                    ("abk", "Абхазский"),
                    ("aze", "Азербайджанский"),
                    ("alb", "Албанский"),
                    ("amh", "Амхарский"),
                    ("eng", "Английский"),
                    ("ara", "Арабский"),
                    ("arm", "Армянский"),
                    ("ben", "Бенгальский"),
                    ("bul", "Болгарский"),
                    ("hun", "Венгерский"),
                    ("vie", "Вьетнамский"),
                    ("dut", "Голландский"),
                    ("gre", "Греческий"),
                    ("geo", "Грузинский"),
                    ("dag", "Дагестанский"),
                    ("dar", "Дари"),
                    ("heb", "Иврит"),
                    ("ind", "Индонезийский"),
                    ("spa", "Испанский"),
                    ("ita", "Итальянский"),
                    ("kaz", "Казахский"),
                    ("chi", "Китайский"),
                    ("kor", "Корейский"),
                    ("kur", "Курдский"),
                    ("khm", "Кхмерский"),
                    ("lao", "Лаосский"),
                    ("mac", "Македонский"),
                    ("mon", "Монгольский"),
                    ("ger", "Немецкий"),
                    ("nep", "Непальский"),
                    ("nor", "Норвежский"),
                    ("por", "Португальский"),
                    ("pas", "Пушту"),
                    ("rom", "Румынский"),
                    ("ser", "Сербский"),
                    ("svk", "Словацкий"),
                    ("slo", "Словенский"),
                    ("taj", "Таджикский"),
                    ("tha", "Тайский"),
                    ("tur", "Турецкий"),
                    ("turkmen", "Туркменский"),
                    ("uzb", "Узбекский"),
                    ("urd", "Урду"),
                    ("far", "Фарси"),
                    ("fin", "Финский"),
                    ("fr", "Французский"),
                    ("hin", "Хинди"),
                    ("cro", "Хорватский"),
                    ("sho", "Чешский"),
                    ("swe", "Шведский"),
                    ("shona", "Шона"),
                    ("est", "Эстонский"),
                    ("jap", "Японский"),
                ],
                db_index=True,
                default="eng",
                max_length=10,
                null=True,
                verbose_name="Родной язык",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="favorite",
            field=models.BooleanField(default=False, verbose_name="Избранное"),
        ),
        migrations.AlterField(
            model_name="author",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужской"), ("F", "Женский"), ("O", "Неизвестно")],
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="language_background",
            field=models.CharField(
                choices=[("H", "Эритажный"), ("F", "Иностранный")],
                max_length=10,
                verbose_name="Тип носителя",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="language_level",
            field=models.CharField(
                choices=[
                    (
                        "Beginner",
                        (
                            ("NL", "Novice Low"),
                            ("NM", "Novice Middle"),
                            ("NH", "Novice High"),
                            ("A1", "A1"),
                            ("A2", "A2"),
                        ),
                    ),
                    (
                        "Intermediate",
                        (
                            ("IL", "Intermediate Low"),
                            ("IM", "Intermediate Middle"),
                            ("IH", "Intermediate High"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                        ),
                    ),
                    (
                        "Advanced",
                        (
                            ("AL", "Advanced Low"),
                            ("AM", "Advanced Middle"),
                            ("AH", "Advanced High"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ),
                    ),
                    ("Other", "Other"),
                ],
                db_index=True,
                max_length=10,
                null=True,
                verbose_name="Уровень владения языком",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="author",
            name="program",
            field=models.CharField(max_length=255, verbose_name="Программа"),
        ),
        migrations.AlterField(
            model_name="document",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corpus.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="body",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="document",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="document",
            name="date",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год написания"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("answers", "Ответы на вопросы"),
                    ("nonacademic", "Неакадемическое эссе"),
                    ("academic", "Академическое эссе"),
                    ("blog", "Блог"),
                    ("letter", "Письмо"),
                    ("story", "История"),
                    ("paraphrase", "Пересказ"),
                    ("definition", "Определение"),
                    ("bio", "Биография"),
                    ("description", "Описание"),
                    ("summary", "Краткое изложение"),
                    ("other", "Другое"),
                ],
                db_index=True,
                default="other",
                max_length=100,
                null=True,
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Источник"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Новый"), (1, "Аннотированный"), (2, "Проверенный")],
                default=0,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="subcorpus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HSE", "HSE"),
                    ("UNICE", "UNICE"),
                    ("RULEC", "RULEC"),
                    ("FIN", "FIN"),
                    ("BERLIN", "BERLIN"),
                    ("TOKYO", "TOKYO"),
                    ("SFEDU", "SFEDU"),
                ],
                db_index=True,
                default="HSE",
                max_length=10,
                null=True,
                verbose_name="Подкорпус",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="corpus.document",
                verbose_name="Документ",
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="markup",
            field=models.TextField(blank=True, null=True, verbose_name="Разметка"),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="number",
            field=models.IntegerField(verbose_name="Номер в тексте"),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
    ]
