# Generated by Django 4.2 on 2023-04-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corpus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="corpus.document"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="guid",
            field=models.CharField(
                db_index=True, editable=False, max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="sentence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="corpus.sentence"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="corpus.document"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="sentence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="corpus.sentence"
            ),
        ),
        migrations.CreateModel(
            name="Morphology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lemma", models.CharField(db_index=True, max_length=200)),
                ("part_of_speech", models.CharField(db_index=True, max_length=200)),
                ("grammemes", models.CharField(db_index=True, max_length=200)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="corpus.token"
                    ),
                ),
            ],
            options={
                "verbose_name": "analysis",
                "verbose_name_plural": "analyses",
            },
        ),
    ]
