# Generated by Django 4.2.3 on 2023-08-14 10:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="words",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="sentence_num",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="token_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
