# Generated by Django 4.2 on 2023-05-04 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0002_alter_annotation_alt_alter_annotation_document_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentence",
            options={"ordering": ["number"]},
        ),
    ]
