# Generated by Django 4.2 on 2023-05-04 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0003_alter_sentence_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentence",
            options={},
        ),
    ]
