# Generated by Django 4.2 on 2023-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0003_alter_document_author_alter_document_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="dominant_language",
            field=models.CharField(
                choices=[
                    ("abk", "Abkhaz"),
                    ("alb", "Albanian"),
                    ("amh", "Amharic"),
                    ("ara", "Arabic"),
                    ("arm", "Armenian"),
                    ("aze", "Azerbaijani"),
                    ("ben", "Bengali"),
                    ("bul", "Bulgarian"),
                    ("chi", "Chinese"),
                    ("cro", "Croatian"),
                    ("sho", "Czech"),
                    ("dag", "Dagestanian"),
                    ("dar", "Dari"),
                    ("dut", "Dutch"),
                    ("eng", "English"),
                    ("est", "Estonian"),
                    ("far", "Farsi"),
                    ("fin", "Finnish"),
                    ("fr", "French"),
                    ("geo", "Georgian"),
                    ("ger", "German"),
                    ("gre", "Greek"),
                    ("heb", "Hebrew"),
                    ("hin", "Hindi"),
                    ("hun", "Hungarian"),
                    ("ind", "Indonesian"),
                    ("ita", "Italian"),
                    ("jap", "Japanese"),
                    ("kaz", "Kazakh"),
                    ("khm", "Khmer"),
                    ("kor", "Korean"),
                    ("kur", "Kurdish"),
                    ("lao", "Lao"),
                    ("mac", "Macedonian"),
                    ("mon", "Mongolian"),
                    ("nep", "Nepali"),
                    ("nor", "Norwegian"),
                    ("pas", "Pashto"),
                    ("por", "Portuguese"),
                    ("rom", "Romanian"),
                    ("ser", "Serbian"),
                    ("sho", "Shona"),
                    ("svk", "Slovak"),
                    ("slo", "Slovene"),
                    ("spa", "Spanish"),
                    ("swe", "Swedish"),
                    ("taj", "Tajik"),
                    ("tha", "Thai"),
                    ("tur", "Turkish"),
                    ("turkmen", "Turkmen"),
                    ("urd", "Urdu"),
                    ("uzb", "Uzbek"),
                    ("vie", "Vietnamese"),
                ],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="language_level",
            field=models.CharField(
                choices=[
                    (
                        "Beginner",
                        (
                            ("NL", "Novice Low"),
                            ("NM", "Novice Middle"),
                            ("NH", "Novice High"),
                            ("A1", "A1"),
                            ("A2", "A2"),
                        ),
                    ),
                    (
                        "Intermediate",
                        (
                            ("IL", "Intermediate Low"),
                            ("IM", "Intermediate Middle"),
                            ("IH", "Intermediate High"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                        ),
                    ),
                    (
                        "Advanced",
                        (
                            ("AL", "Advanced Low"),
                            ("AM", "Advanced Middle"),
                            ("AH", "Advanced High"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ),
                    ),
                    ("Other", "Other"),
                ],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
    ]
