# Generated by Django 4.2 on 2023-04-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0004_alter_author_dominant_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
