# Generated by Django 4.2 on 2023-05-06 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("corpus", "0005_document_oral_document_time_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="annotators",
            field=models.ManyToManyField(
                blank=True,
                related_name="annotated_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Аннотаторы",
            ),
        ),
    ]
