# Generated by Django 4.2 on 2023-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0005_document_favorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="favorite",
        ),
        migrations.AddField(
            model_name="author",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
