# Generated by Django 4.2.1 on 2023-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0008_token_number_alter_author_dominant_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="feats",
        ),
        migrations.AddField(
            model_name="token",
            name="animate",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[("Cmp", "Cmp"), ("Pos", "Pos"), ("Sup", "Sup")],
                db_index=True,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="foreign",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Fem", "Fem"), ("Masc", "Masc"), ("Neut", "Neut")],
                db_index=True,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="gram_case",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Acc", "Acc"),
                    ("Dat", "Dat"),
                    ("Gen", "Gen"),
                    ("Ins", "Ins"),
                    ("Loc", "Loc"),
                    ("Nom", "Nom"),
                    ("Par", "Par"),
                    ("Voc", "Voc"),
                ],
                db_index=True,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="hyph",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[("Cnd", "Cnd"), ("Imp", "Imp"), ("Ind", "Ind")],
                db_index=True,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="negative",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="perfect",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="person",
            field=models.CharField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3")],
                db_index=True,
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="plural",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="short",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="tense",
            field=models.CharField(
                blank=True,
                choices=[("Fut", "Fut"), ("Past", "Past"), ("Pres", "Pres")],
                db_index=True,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="verb_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Conv", "Conv"),
                    ("Fin", "Fin"),
                    ("Inf", "Inf"),
                    ("Part", "Part"),
                ],
                db_index=True,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="voice",
            field=models.CharField(
                blank=True,
                choices=[("Act", "Act"), ("Mid", "Mid"), ("Pass", "Pass")],
                db_index=True,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="lemma",
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="pos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADJ", "ADJ"),
                    ("ADP", "ADP"),
                    ("ADV", "ADV"),
                    ("AUX", "AUX"),
                    ("CCONJ", "CCONJ"),
                    ("DET", "DET"),
                    ("INTJ", "INTJ"),
                    ("NOUN", "NOUN"),
                    ("NUM", "NUM"),
                    ("PART", "PART"),
                    ("PRON", "PRON"),
                    ("PROPN", "PROPN"),
                    ("PUNCT", "PUNCT"),
                    ("SCONJ", "SCONJ"),
                    ("SYM", "SYM"),
                    ("VERB", "VERB"),
                    ("X", "X"),
                ],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
