# Generated by Django 4.2.2 on 2023-07-13 06:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0010_annotation_end_annotation_start_annotation_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="token_texts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(db_index=True, max_length=200),
                null=True,
                size=None,
            ),
        ),
    ]
