# Generated by Django 4.2.2 on 2023-07-13 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0012_remove_sentence_token_texts_sentence_tokens_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentence",
            name="tokens_str",
        ),
        migrations.AddField(
            model_name="sentence",
            name="lemmas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
    ]
